### ISSUE TITLE
Rectangular Slit with CUDA

### ISSUE THREAD

**Issue by ethan-becker-fathom** [rafael-fuente/Diffraction-Simulations--Angular-Spectrum-Method#5]
Running a rectungular slit with CUDA backend gives me the following error:

> Traceback (most recent call last):
>   File "C:/Users/ethan/Documents/PycharmProjects/diffraction/examples/circular_aperture_lens.py", line 27, in <module>
>     F.add_rectangular_slit(x0=0, y0=0, width=1.5 * mm, height=1.5 * mm)
>   File "C:\Users\ethan\Documents\PycharmProjects\diffraction\venv\lib\site-packages\diffractsim\monochromatic_simulator.py", line 68, in add_rectangular_slit
>     [bd.ones(self.E.shape), bd.zeros(self.E.shape)],
>   File "C:\Users\ethan\Documents\PycharmProjects\diffraction\venv\lib\site-packages\cupy\_indexing\indexing.py", line 199, in select
>     if cond.dtype.type is not cupy.bool_:
> AttributeError: 'bool' object has no attribute 'dtype'

Can be fixed by modifying assignment if the 't' variable in the 'add_rectangular_slit' function.

```
t = bd.select(
            [
                ((self.xx > (x0 - width / 2)) & (self.xx < (x0 + width / 2)))
                & ((self.yy > (y0 - height / 2)) & (self.yy < (y0 + height / 2))),
                bd.full(self.E.shape, True, dtype=bool)
            ],
            [bd.ones(self.E.shape), bd.zeros(self.E.shape)],
        )
```

**Comment by rafael-fuente** [comment]
Thank you for noticing the bug. It's fixed in the new update.
